name: Deploy
on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
    # environment: Production # Preview

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Create a file
        env:
          MY_MSG: ${{ vars.MY_MSG }}
        run: echo "$MY_MSG" > data.txt

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "dannygim-fresh-demo"
          entrypoint: "./main.ts"
